services:
  app:
    build: .
    working_dir: /api
    container_name: 'app'
    command: >
      sh -c "python manage.py migrate &&
             python run.py &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/api
      - app_logs:/api/logs  # Agregar este volumen
    environment:
      - PYTHONPATH=/api
      - DB_HOST=terraform-20250329031442116000000002.ccfduvi3vksv.us-east-1.rds.amazonaws.com
      - DB_NAME=appdb
      - DB_USER=postgres
      - DB_PASSWORD=SuperSecret123PASSWORD
    networks:
      - app-network

volumes:
  postgres_data:
  app_logs:  # Agregar este volumen
    driver: local

networks:
  app-network:
    driver: bridge